on:
  pull_request: 
    branches: ["main", "test/testing-branch"]
  push:
    branches: ["main", "test/testing-branch"]
  
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint HTML
        run: npm run lint:html

      - name: Security Audit
        run: npm audit --audit-level=low

  backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - name: Run Node.js Unit Tests
        run: npm run test

  e2e-browser-tests:
    needs: backend-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start Node.js Server
        run: node server.js &
        env:
          PORT: 3000

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run E2E Tests (Playwright)
        run: npx playwright test

