on:
  pull_request: 
    branches: ["main", "test/testing-branch"]
  push:
    branches: ["main", "test/testing-branch"]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Завантажити код
        uses: actions/checkout@v5

      - name: Встановити Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Встановити залежності
        run: npm ci

